# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 370cc2a10b294437cd629e4d999516caf018e4042733145e9658e4f5afd800c58cb8929e87a9b89e16201dc7e7962b36d450a73831d20308b12239b0823b1a66

test:
  secret_key_base: 94439aa918800a9d37a236fc9d72ad951db7e8729c9eb915ce19c690d05ba4e271f4e51fc1abf8de8871039f7035a1335472f11e892e953affa4d5eef1590910

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
